# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: push

jobs:
  build:
    name: Setup, Lint, Type check, Build, Test, Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          version: 12.x
    
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint --if-present
      
      - name: Type check
        run: npm run type-check --if-present
        
#       - name: Test
#         run: npm test

      - name: Build
        run: npm run build
